[package]
name = "one_at_a_time_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.39"
quote = "1.0.18"

[dev-dependencies]
pretty_assertions = "1.0.0"
